marketing_insights:
  outputs:
    ci:
      account: EBIUGTJ-FN06775
      database: MARKETING_INSIGHTS_CI
      private_key_path: {{ env_var('DBT_PRIVATE_KEY_PATH') }}
      role: ACCOUNTADMIN
      schema: ANALYTICS_CI
      threads: 1
      type: snowflake
      user: KIRANPOTHINA
      warehouse: COMPUTE_WH
  target: ci